/**
 * server/db/postgresql/schema_catalog.js
 * ======================================
 * Complete catalog of all SQLite tables in the CACC Writer system.
 * Each table is documented with source location, columns, indexes, and constraints.
 * Used for schema translation and migration planning.
 */

export const SCHEMA_CATALOG = {
  tables: [
    // ════════════════════════════════════════════════════════════════════════════
    // CORE ASSIGNMENT & CASE MANAGEMENT (server/db/schema.js)
    // ════════════════════════════════════════════════════════════════════════════

    {
      name: 'assignments',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'case_id', sqliteType: 'TEXT NOT NULL UNIQUE', pgType: 'TEXT NOT NULL UNIQUE' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'context_json', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: ['idx_assignments_case_id ON assignments(case_id)'],
      constraints: ['UNIQUE(case_id)'],
    },

    {
      name: 'case_records',
      source: 'server/db/schema.js',
      columns: [
        { name: 'case_id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'status', sqliteType: "TEXT NOT NULL DEFAULT 'active'", pgType: "TEXT NOT NULL DEFAULT 'active'" },
        { name: 'pipeline_stage', sqliteType: "TEXT NOT NULL DEFAULT 'intake'", pgType: "TEXT NOT NULL DEFAULT 'intake'" },
        { name: 'workflow_status', sqliteType: "TEXT NOT NULL DEFAULT 'facts_incomplete'", pgType: "TEXT NOT NULL DEFAULT 'facts_incomplete'" },
        { name: 'address', sqliteType: "TEXT NOT NULL DEFAULT ''", pgType: "TEXT NOT NULL DEFAULT ''" },
        { name: 'borrower', sqliteType: "TEXT NOT NULL DEFAULT ''", pgType: "TEXT NOT NULL DEFAULT ''" },
        { name: 'unresolved_issues_json', sqliteType: "TEXT NOT NULL DEFAULT '[]'", pgType: "TEXT NOT NULL DEFAULT '[]'" },
        { name: 'meta_json', sqliteType: "TEXT NOT NULL DEFAULT '{}'", pgType: "TEXT NOT NULL DEFAULT '{}'" },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: ['idx_case_records_updated_at ON case_records(updated_at)'],
      constraints: [],
    },

    {
      name: 'case_facts',
      source: 'server/db/schema.js',
      columns: [
        { name: 'case_id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'facts_json', sqliteType: "TEXT NOT NULL DEFAULT '{}'", pgType: "TEXT NOT NULL DEFAULT '{}'" },
        { name: 'provenance_json', sqliteType: "TEXT NOT NULL DEFAULT '{}'", pgType: "TEXT NOT NULL DEFAULT '{}'" },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [],
      constraints: ['FOREIGN KEY (case_id) REFERENCES case_records(case_id) ON DELETE CASCADE'],
    },

    {
      name: 'case_outputs',
      source: 'server/db/schema.js',
      columns: [
        { name: 'case_id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'outputs_json', sqliteType: "TEXT NOT NULL DEFAULT '{}'", pgType: "TEXT NOT NULL DEFAULT '{}'" },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [],
      constraints: ['FOREIGN KEY (case_id) REFERENCES case_records(case_id) ON DELETE CASCADE'],
    },

    {
      name: 'case_history',
      source: 'server/db/schema.js',
      columns: [
        { name: 'case_id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'history_json', sqliteType: "TEXT NOT NULL DEFAULT '{}'", pgType: "TEXT NOT NULL DEFAULT '{}'" },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [],
      constraints: ['FOREIGN KEY (case_id) REFERENCES case_records(case_id) ON DELETE CASCADE'],
    },

    // ════════════════════════════════════════════════════════════════════════════
    // REPORT PLANNING & GENERATION (server/db/schema.js)
    // ════════════════════════════════════════════════════════════════════════════

    {
      name: 'report_plans',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'assignment_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'plan_json', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: ['idx_report_plans_assignment_id ON report_plans(assignment_id)'],
      constraints: ['FOREIGN KEY (assignment_id) REFERENCES assignments(id)'],
    },

    {
      name: 'generation_runs',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'case_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'assignment_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'status', sqliteType: "TEXT NOT NULL DEFAULT 'pending'", pgType: "TEXT NOT NULL DEFAULT 'pending'" },
        { name: 'started_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'completed_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'duration_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'context_build_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'report_plan_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'retrieval_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'analysis_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'parallel_draft_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'validation_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'assembly_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'section_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'success_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'error_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'retry_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'partial_complete', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'retrieval_cache_hit', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'memory_items_scanned', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'memory_items_used', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'warnings_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'metrics_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'error_text', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'voice_profile_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'retrieval_pack_version', sqliteType: "TEXT DEFAULT 'v1'", pgType: "TEXT DEFAULT 'v1'" },
        { name: 'draft_package_json', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_generation_runs_case_id ON generation_runs(case_id)',
        'idx_generation_runs_status ON generation_runs(status)',
      ],
      constraints: [],
    },

    {
      name: 'section_jobs',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'run_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'section_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'status', sqliteType: "TEXT NOT NULL DEFAULT 'pending'", pgType: "TEXT NOT NULL DEFAULT 'pending'" },
        { name: 'generator_profile', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'prompt_version', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'dependencies_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'section_policy_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'dependency_snapshot_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'attempt_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'started_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'completed_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'duration_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'dependency_wait_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'input_chars', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'output_chars', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'warnings_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'prompt_tokens', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'completion_tokens', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'error_text', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'retrieval_source_ids_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'estimated_cost_usd', sqliteType: 'REAL', pgType: 'DOUBLE PRECISION' },
        { name: 'voice_hints_json', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'retrieval_score_json', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_section_jobs_run_id ON section_jobs(run_id)',
        'idx_section_jobs_status ON section_jobs(status)',
      ],
      constraints: ['FOREIGN KEY (run_id) REFERENCES generation_runs(id)'],
    },

    {
      name: 'generated_sections',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'job_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'run_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'case_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'section_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'draft_text', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'reviewed_text', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'final_text', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'audit_metadata_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'quality_score', sqliteType: 'REAL', pgType: 'DOUBLE PRECISION' },
        { name: 'quality_metadata_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'examples_used', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'approved', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'approved_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'inserted_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'promoted_approved_memory_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'prompt_version', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'section_policy_json', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'dependency_snapshot_json', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'quality_factors_json', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'freshness_status', sqliteType: "TEXT DEFAULT 'current'", pgType: "TEXT DEFAULT 'current'" },
        { name: 'stale_reason', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'stale_since', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'regeneration_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_generated_sections_case_id ON generated_sections(case_id)',
        'idx_generated_sections_run_id ON generated_sections(run_id)',
        'idx_generated_sections_section_id ON generated_sections(section_id, case_id)',
      ],
      constraints: ['FOREIGN KEY (job_id) REFERENCES section_jobs(id)'],
    },

    // ════════════════════════════════════════════════════════════════════════════
    // MEMORY & RETRIEVAL (server/db/schema.js)
    // ════════════════════════════════════════════════════════════════════════════

    {
      name: 'memory_items',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'section_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text_hash', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'source_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'quality_score', sqliteType: 'REAL DEFAULT 75', pgType: 'DOUBLE PRECISION DEFAULT 75' },
        { name: 'approved', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'staged', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'property_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'market_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'city', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'county', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'state', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'assignment_purpose', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'loan_program', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'subject_condition', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'tags_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'metadata_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'source_file', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_report_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_memory_items_hash ON memory_items(text_hash)',
        'idx_memory_items_section_form ON memory_items(section_type, form_type)',
        'idx_memory_items_approved ON memory_items(approved, quality_score)',
      ],
      constraints: [],
    },

    {
      name: 'retrieval_cache',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'assignment_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'section_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'pack_json', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'expires_at', sqliteType: 'TEXT NOT NULL', pgType: 'TIMESTAMPTZ NOT NULL' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_retrieval_cache_assignment ON retrieval_cache(assignment_id, section_id)',
        'idx_retrieval_cache_expires ON retrieval_cache(expires_at)',
      ],
      constraints: [],
    },

    {
      name: 'analysis_artifacts',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'run_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'artifact_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'section_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'data_json', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'duration_ms', sqliteType: 'INTEGER', pgType: 'INTEGER' },
        { name: 'warnings_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: ['idx_analysis_artifacts_run_id ON analysis_artifacts(run_id)'],
      constraints: ['FOREIGN KEY (run_id) REFERENCES generation_runs(id)'],
    },

    {
      name: 'ingest_jobs',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'source_file', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'status', sqliteType: "TEXT NOT NULL DEFAULT 'pending'", pgType: "TEXT NOT NULL DEFAULT 'pending'" },
        { name: 'sections_extracted', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'phrases_extracted', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'error_text', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'started_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'completed_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: ['idx_ingest_jobs_status ON ingest_jobs(status)'],
      constraints: [],
    },

    {
      name: 'staged_memory_reviews',
      source: 'server/db/schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'ingest_job_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'section_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'form_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text_hash', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'source_file', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'metadata_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'review_status', sqliteType: "TEXT DEFAULT 'pending'", pgType: "TEXT DEFAULT 'pending'" },
        { name: 'reviewed_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'promoted_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_staged_reviews_status ON staged_memory_reviews(review_status)',
        'idx_staged_reviews_form ON staged_memory_reviews(form_type, section_type)',
      ],
      constraints: [],
    },

    // ════════════════════════════════════════════════════════════════════════════
    // PHASE 6: VOICE & APPROVED MEMORY
    // ════════════════════════════════════════════════════════════════════════════

    {
      name: 'approved_memory',
      source: 'server/migration/phase6Schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'bucket', sqliteType: "TEXT NOT NULL DEFAULT 'narrative_section'", pgType: "TEXT NOT NULL DEFAULT 'narrative_section'" },
        { name: 'source_type', sqliteType: "TEXT NOT NULL DEFAULT 'imported'", pgType: "TEXT NOT NULL DEFAULT 'imported'" },
        { name: 'text', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text_hash', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'source_document_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_run_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_section_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'case_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'report_family', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'form_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'property_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'assignment_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'canonical_field_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'section_group', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'market_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'county', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'city', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'state', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'loan_program', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'subject_condition', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'style_tags_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'issue_tags_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'quality_score', sqliteType: 'REAL DEFAULT 75', pgType: 'DOUBLE PRECISION DEFAULT 75' },
        { name: 'approval_status', sqliteType: "TEXT DEFAULT 'approved'", pgType: "TEXT DEFAULT 'approved'" },
        { name: 'approval_timestamp', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'approved_by', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'provenance_note', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'notes', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'active', sqliteType: 'INTEGER DEFAULT 1', pgType: 'INTEGER DEFAULT 1' },
        { name: 'pinned', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_approved_memory_hash ON approved_memory(text_hash)',
        'idx_approved_memory_bucket ON approved_memory(bucket, active)',
        'idx_approved_memory_field ON approved_memory(canonical_field_id, form_type, active)',
        'idx_approved_memory_family ON approved_memory(report_family, active)',
        'idx_approved_memory_approval ON approved_memory(approval_status, active)',
        'idx_approved_memory_quality ON approved_memory(quality_score DESC)',
        'idx_approved_memory_source ON approved_memory(source_type, active)',
      ],
      constraints: ['UNIQUE(text_hash)'],
    },

    {
      name: 'voice_profiles',
      source: 'server/migration/phase6Schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'name', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'scope', sqliteType: "TEXT NOT NULL DEFAULT 'global'", pgType: "TEXT NOT NULL DEFAULT 'global'" },
        { name: 'report_family', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'canonical_field_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'tone', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'sentence_length', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'hedging_degree', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'terminology_preference', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'reconciliation_style', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'section_opening_style', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'section_closing_style', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'preferred_phrases_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'forbidden_phrases_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'phrasing_patterns_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'custom_dimensions_json', sqliteType: "TEXT DEFAULT '{}'", pgType: "TEXT DEFAULT '{}'" },
        { name: 'active', sqliteType: 'INTEGER DEFAULT 1', pgType: 'INTEGER DEFAULT 1' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_voice_profiles_scope ON voice_profiles(scope, active)',
        'idx_voice_profiles_family ON voice_profiles(report_family, active)',
        'idx_voice_profiles_field ON voice_profiles(canonical_field_id, active)',
      ],
      constraints: [],
    },

    {
      name: 'voice_rules',
      source: 'server/migration/phase6Schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'profile_id', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'rule_type', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'rule_value', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'priority', sqliteType: 'INTEGER DEFAULT 50', pgType: 'INTEGER DEFAULT 50' },
        { name: 'canonical_field_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'notes', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'active', sqliteType: 'INTEGER DEFAULT 1', pgType: 'INTEGER DEFAULT 1' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_voice_rules_profile ON voice_rules(profile_id, active)',
        'idx_voice_rules_type ON voice_rules(rule_type, active)',
        'idx_voice_rules_field ON voice_rules(canonical_field_id, active)',
      ],
      constraints: ['FOREIGN KEY (profile_id) REFERENCES voice_profiles(id)'],
    },

    {
      name: 'comp_commentary_memory',
      source: 'server/migration/phase6Schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'text', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text_hash', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'commentary_type', sqliteType: "TEXT NOT NULL DEFAULT 'general'", pgType: "TEXT NOT NULL DEFAULT 'general'" },
        { name: 'subject_property_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'comp_property_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'market_density', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'urban_suburban_rural', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'report_family', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'form_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'canonical_field_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'issue_tags_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'adjustment_categories_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'quality_score', sqliteType: 'REAL DEFAULT 75', pgType: 'DOUBLE PRECISION DEFAULT 75' },
        { name: 'approval_status', sqliteType: "TEXT DEFAULT 'approved'", pgType: "TEXT DEFAULT 'approved'" },
        { name: 'approved_by', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_document_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_run_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'case_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'provenance_note', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'active', sqliteType: 'INTEGER DEFAULT 1', pgType: 'INTEGER DEFAULT 1' },
        { name: 'pinned', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_comp_commentary_hash ON comp_commentary_memory(text_hash)',
        'idx_comp_commentary_type ON comp_commentary_memory(commentary_type, active)',
        'idx_comp_commentary_family ON comp_commentary_memory(report_family, active)',
        'idx_comp_commentary_quality ON comp_commentary_memory(quality_score DESC)',
      ],
      constraints: ['UNIQUE(text_hash)'],
    },

    {
      name: 'memory_staging_candidates',
      source: 'server/migration/phase6Schema.js',
      columns: [
        { name: 'id', sqliteType: 'TEXT PRIMARY KEY', pgType: 'TEXT PRIMARY KEY' },
        { name: 'candidate_source', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'text_hash', sqliteType: 'TEXT NOT NULL', pgType: 'TEXT NOT NULL' },
        { name: 'target_bucket', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'canonical_field_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'report_family', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'form_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'property_type', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'case_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_document_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_run_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'source_section_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'style_tags_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'issue_tags_json', sqliteType: "TEXT DEFAULT '[]'", pgType: "TEXT DEFAULT '[]'" },
        { name: 'quality_score', sqliteType: 'REAL DEFAULT 50', pgType: 'DOUBLE PRECISION DEFAULT 50' },
        { name: 'word_count', sqliteType: 'INTEGER DEFAULT 0', pgType: 'INTEGER DEFAULT 0' },
        { name: 'review_status', sqliteType: "TEXT DEFAULT 'pending'", pgType: "TEXT DEFAULT 'pending'" },
        { name: 'reviewed_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'reviewed_by', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'review_notes', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'promoted_memory_id', sqliteType: 'TEXT', pgType: 'TEXT' },
        { name: 'promoted_at', sqliteType: 'TEXT', pgType: 'TIMESTAMPTZ' },
        { name: 'created_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
        { name: 'updated_at', sqliteType: "TEXT NOT NULL DEFAULT (datetime('now'))", pgType: 'TIMESTAMPTZ DEFAULT NOW()' },
      ],
      indexes: [
        'idx_staging_candidates_status ON memory_staging_candidates(review_status)',
        'idx_staging_candidates_source ON memory_staging_candidates(candidate_source, review_status)',
        'idx_staging_candidates_field ON memory_staging_candidates(canonical_field_id, review_status)',
        'idx_staging_candidates_hash ON memory_staging_candidates(text_hash)',
      ],
      constraints: [],
    },

    // ════════════════════════════════════════════════════════════════════════════
    // REMAINING TABLES (Phase 7-20, Pipeline, Brain)
    // ════════════════════════════════════════════════════════════════════════════
    // [Continuing in next section due to length...]
  ]
};

// Table count for verification
export const TABLE_COUNT = SCHEMA_CATALOG.tables.length;

export default { SCHEMA_CATALOG, TABLE_COUNT };
