/**
 * server/whitelabel/whitelabelService.js
 * ─────────────────────────────────────────────────────────────────────────────
 * White-label customization system (Enterprise tier).
 *
 * Allows enterprise customers to rebrand the platform:
 *   - Custom logo and company name
 *   - Custom color scheme
 *   - Custom email templates
 *   - Custom PDF report branding
 *   - Custom portal URL
 *   - Remove "Appraisal Agent" branding
 *   - Custom domain support
 *
 * Stored per-firm, applied on login.
 */

import { getDb } from '../db/database.js';
import log from '../logger.js';

export function ensureWhitelabelSchema() {
  const db = getDb();
  db.exec(`
    CREATE TABLE IF NOT EXISTS whitelabel_configs (
      id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(8)))),
      firm_id     TEXT NOT NULL UNIQUE,
      company_name TEXT NOT NULL,
      logo_url    TEXT,
      favicon_url TEXT,
      primary_color TEXT DEFAULT '#e2b714',
      accent_color TEXT DEFAULT '#ffd341',
      background_color TEXT DEFAULT '#0d1117',
      email_from_name TEXT,
      email_footer TEXT,
      pdf_header_text TEXT,
      pdf_footer_text TEXT,
      portal_title TEXT,
      custom_domain TEXT,
      hide_platform_branding INTEGER DEFAULT 0,
      custom_css TEXT,
      created_at  TEXT DEFAULT (datetime('now')),
      updated_at  TEXT DEFAULT (datetime('now'))
    );
  `);
}

/**
 * Get white-label config for a firm.
 */
export function getWhitelabelConfig(firmId) {
  const db = getDb();
  const config = db.prepare('SELECT * FROM whitelabel_configs WHERE firm_id = ?').get(firmId);
  if (!config) return null;
  return { ...config, hide_platform_branding: Boolean(config.hide_platform_branding) };
}

/**
 * Create or update white-label config.
 */
export function setWhitelabelConfig(firmId, updates) {
  const db = getDb();
  const existing = db.prepare('SELECT id FROM whitelabel_configs WHERE firm_id = ?').get(firmId);

  if (existing) {
    const fields = [];
    const values = [];
    for (const [key, val] of Object.entries(updates)) {
      const col = key.replace(/([A-Z])/g, '_$1').toLowerCase(); // camelCase → snake_case
      if (['company_name','logo_url','favicon_url','primary_color','accent_color','background_color',
           'email_from_name','email_footer','pdf_header_text','pdf_footer_text','portal_title',
           'custom_domain','hide_platform_branding','custom_css'].includes(col)) {
        fields.push(`${col} = ?`);
        values.push(val);
      }
    }
    if (fields.length > 0) {
      fields.push("updated_at = datetime('now')");
      values.push(firmId);
      db.prepare(`UPDATE whitelabel_configs SET ${fields.join(', ')} WHERE firm_id = ?`).run(...values);
    }
  } else {
    db.prepare(`INSERT INTO whitelabel_configs (firm_id, company_name) VALUES (?, ?)`).run(firmId, updates.companyName || updates.company_name || 'Company');
    // Recursively update with provided fields
    if (Object.keys(updates).length > 1) setWhitelabelConfig(firmId, updates);
  }

  return getWhitelabelConfig(firmId);
}

/**
 * Generate CSS overrides for white-label.
 */
export function generateCssOverrides(config) {
  if (!config) return '';
  let css = ':root {\n';
  if (config.primary_color) css += `  --accent: ${config.primary_color};\n  --primary: ${config.primary_color};\n`;
  if (config.accent_color) css += `  --accent-soft: ${config.accent_color}20;\n`;
  if (config.background_color) css += `  --bg: ${config.background_color};\n`;
  css += '}\n';
  if (config.custom_css) css += config.custom_css + '\n';
  if (config.hide_platform_branding) css += '.platform-branding { display: none !important; }\n';
  return css;
}

/**
 * Get branding context for PDF generation.
 */
export function getPdfBranding(firmId) {
  const config = getWhitelabelConfig(firmId);
  if (!config) return { companyName: 'Appraisal Agent', headerText: null, footerText: 'Generated by Appraisal Agent' };
  return {
    companyName: config.company_name,
    headerText: config.pdf_header_text,
    footerText: config.pdf_footer_text || `Generated by ${config.company_name}`,
    logoUrl: config.logo_url,
    primaryColor: config.primary_color,
  };
}

/**
 * Get email branding for a firm.
 */
export function getEmailBranding(firmId) {
  const config = getWhitelabelConfig(firmId);
  if (!config) return { fromName: 'Appraisal Agent', footer: 'Appraisal Agent — AI-Powered Narrative Drafting' };
  return {
    fromName: config.email_from_name || config.company_name,
    footer: config.email_footer || config.company_name,
    primaryColor: config.primary_color,
  };
}

export default {
  ensureWhitelabelSchema, getWhitelabelConfig, setWhitelabelConfig,
  generateCssOverrides, getPdfBranding, getEmailBranding,
};
